spring.application.name=votesyss

spring.datasource.url=jdbc:postgresql://dpg-d5ru25jlr7ts7385cf90-a.oregon-postgres.render.com:5432/votesyss
spring.datasource.username=votesyss_user
spring.datasource.password=2RQ1HZXo5g3uDPQg28jOE6nx1Xb5HBdm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rafinhacacador@gmail.com
spring.mail.password=vfvq gjxe rpkc qyxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

votesys.frontend.base-url=http://localhost:5173


spring.secretkey=duwhUWDHUWIADHdhwaudh
spring.tempo_expiracao=5
