# Nome da Aplicação
spring.application.name=votesys

spring.datasource.url=jdbc:postgresql://dpg-d4tkueeuk2gs739flk9g-a.oregon-postgres.render.com/votesys_q8s5
spring.datasource.username=votesys_q8s5_user
spring.datasource.password=fxoUAKAf1OE48QPEQSQ9qSYDp1lHBlu8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rafinhacacador@gmail.com
spring.mail.password=vfvq gjxe rpkc qyxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.secretkey=duwhUWDHUWIADHdhwaudh
spring.tempo_expiracao=5
votesys.frontend.base-url=http://localhost:5173