spring.application.name=votesys

spring.datasource.url=jdbc:postgresql://dpg-d5rtc1n18n1s73d08klg-a.oregon-postgres.render.com:5432/votesys_q8s5?sslmode=require
spring.datasource.username=votesys_q8s5_user

spring.datasource.password=fxoUAKAf10E48QPEQSQ9qSYDp1lHBlu8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rafinhacacador@gmail.com
spring.mail.password=vfvq gjxe rpkc qyxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


votesys.frontend.base-url=http://localhost:5173
spring.secretkey=duwhUWDHUWIADHdhwaudh
spring.tempo_expiracao=5